---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: amq-console
  labels:
    app: sso
spec:
  realmSelector:
     matchLabels:
      app: sso
  roles:
    - name: admin
    - name: viewer
  client:
    clientId: amq-console
    name: amq-console
    description: Client to manage access of AMQ Broker Management Consoles
    protocol: openid-connect
    publicClient: true
    standardFlowEnabled: true
    directAccessGrantsEnabled: false
    serviceAccountsEnabled: false
    redirectUris:
      - https://ex-aao-wconsj-0-svc-rte-amq-sso.apps.OPENSHIFT-DOMAIN/console/*
      - https://ex-aao-wconsj-1-svc-rte-amq-sso.apps.OPENSHIFT-DOMAIN/console/*
    webOrigins:
      - '+'
    defaultRoles:
      - viewer
    defaultClientScopes:
      - acr
      - email
      - profile
      - roles
      - web-origins
    optionalClientScopes:
      - address
      - microprofile-jwt
      - offline_access
      - phone
