apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: ${BROKER_NAME}-template
metadata:
  annotations:
    description: deployment for ${BROKER_NAME}-template
  name: ${BROKER_NAME}-template
objects:
- apiVersion: broker.amq.io/v1beta1
  kind: ActiveMQArtemis
  metadata:
    name: ${BROKER_NAME}
    application: ${BROKER_NAME}
    labels:
      app: ${BROKER_NAME}
  spec:
    acceptors:
      - name: amq
        expose: true
        protocols: 'amqp,core,stomp'
        port: 61617
        sslEnabled: true
        sslSecret: ${BROKER_NAME}-secret
    adminUser:  admin
    adminPassword: admin
    console:
      expose: true
      sslEnabled: true
      sslSecret: ${BROKER_NAME}-wsconsj
    deploymentPlan:
      size: 1
      image: placeholder
      journalType: aio
      persistenceEnabled: true
 # To specify a size for the persistent storage default is  2 GiB
 #     storage:
 #         size: 10Gi
      messageMigration: true
      requireLogin: false
      enableMetricsPlugin: true
#      resources:
#          limits:
# set to 1 core (1000 microcores) limit
#              cpu: "1000m"
# set to 2 GB limit
#              memory: "2048M"
#          requests:
#              cpu: "500m"
#              memory: "1024M"
parameters:
  - name: BROKER_NAME
    value: "amq-broker"
