apiVersion: broker.amq.io/v1alpha1 
kind: ActiveMQArtemisSecurity
metadata:
  name: keycloak
spec:
  loginModules:
    keycloakLoginModules:
    - name: keycloak-broker 
      moduleType: directAccess
      configuration:
        enableBasicAuth: false
        #authServerUrl: https://ex-aao-wconsj-1-svc-rte-amq-sso.apps.OPENSHIFT-DOMAIN/console/*
        authServerUrl: 'https://keycloak-rh-sso.apps.cluster-jpjnn.jpjnn.sandbox2327.opentlc.com/auth/'
        credentials:
        - key: secret
          value: 0c2edacd-146a-442a-8852-b29d945a96e8
        principalAttribute: preferred_username
        realm: myamq-realm
        resource: artemis-broker
        sslRequired: external
        useResourceRoleMappings: true
    - name: 'keycloak-console'
      moduleType: 'bearerToken'
      configuration:
        enableBasicAuth: false
        realm: myamq-realm
        resource: 'artemis-console'
        publicClient: true
        #authServerUrl: https://ex-aao-wconsj-1-svc-rte-amq-sso.apps.OPENSHIFT-DOMAIN/console/*
        authServerUrl: 'https://keycloak-rh-sso.apps.cluster-jpjnn.jpjnn.sandbox2327.opentlc.com/auth/'
        principalAttribute: 'preferred_username'
        useResourceRoleMappings: true
        sslRequired: all
        confidentialPort: 0
  securityDomains:
    brokerDomain:
      name: 'activemq'
      loginModules:
      - name: 'keycloak-broker'
        reload: true
        flag: 'required'
        debug: true
    consoleDomain:
      name: 'console'
      loginModules:
      - name: 'keycloak-console'
        flag: required
        debug: true
  securitySettings:
    broker:
      - match: '#'
        permissions:
        - operationType: 'createAddress'
          roles:
          - admin
          - producer
          - consumer
        - operationType: 'createDurableQueue'
          roles:
          - admin
          - producer
          - consumer
        - operationType: 'deleteDurableQueue'
          roles:
          - admin
        - operationType: 'createNonDurableQueue'
          roles:
          - admin
          - producer
          - consumer
        - operationType: 'deleteNonDurableQueue'
          roles:
          - admin
        - operationType: 'send'
          roles:
          - admin
          - producer
        - operationType: 'consume'
          roles:
          - admin
          - consumer
    management:
      hawtioRoles:
      - admin
      authorisation:
        allowedList:
        - domain: "hawtio"      
        roleAccess:
        - domain: org.apache.activemq.artemis
          accessList:
          - method: "list*"
            roles:
            - admin
          - method: "get*"
            roles:
            - admin
          - method: "is*"
            roles:
            - admin
          - method: "set*"
            roles:
            - admin
          - method: "browse*"
            roles:
            - admin
          - method: "count*"
            roles:
            - admin
          - method: "*"
            roles:
            - admin