apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: artemis-broker
spec:
  realmSelector:
    matchLabels:
      realm: myamq-realm 
  client:
    clientId: artemis-broker
    enabled: true
    publicClient: false
    clientAuthenticatorType: client-secret
    secret: 0c2edacd-146a-442a-8852-b29d945a96e8
    fullScopeAllowed: true
    directAccessGrantsEnabled: true
    protocol: openid-connect
    defaultClientScopes:
      - web-origins
      - role_list
      - profile
      - roles
      - email
    optionalClientScopes:
      - address
      - phone
      - offline_access
      - microprofile-jwt
  roles:
    - name: admin
    - name: producer
    - name: consumer
