# Keycloak Client for AMQ Broker  
apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: ${BROKER_NAME}-client-broker-template
metadata:
  annotations:
    description: Template for ${BROKER_NAME} (broker) client 
  name: ${BROKER_NAME}-client-broker-template
objects:
  - apiVersion: keycloak.org/v1alpha1
    kind: KeycloakClient
    metadata:
      name: amq-broker
      labels:
        app: ${RH_SSO_NAME}
    spec:
      realmSelector:
        matchLabels:
          realm: ${BROKER_NAME}-realm
      client:
        clientId: amq-broker
        name: amq-broker
        description: Client to consume or publish messages into an AMQ Broker
        enabled: true
        protocol: openid-connect
        clientAuthenticatorType: client-secret
        secret: 0c2edacd-146a-442a-8852-b29d945a96e8
        standardFlowEnabled: false
        directAccessGrantsEnabled: true
        serviceAccountsEnabled: false
        defaultClientScopes:
          - role_list
          - email
          - profile
          - roles
          - web-origins
        optionalClientScopes:
          - address
          - microprofile-jwt
          - offline_access
          - phone
      roles:
        - name: admin
        - name: consumer
        - name: sender
        - name: guest
      defaultRoles:
        - guest

parameters:
  - name: RH_SSO_NAME
    value: keycloak
  - name: BROKER_NAME
    value: my-broker